# PYTHON ASSIGNMENT

Print all prime numbers between input range (Ex – input 20 50, prints all prime numbers between 20 and 50).

In [1]:
start=int(input())
end=int(input())
for n in range(start,end+1):
    count=0
    for i in range(1,n+1):
        if(n % i == 0):
            count+=1
    if count==2:
        print(n,end=" ")

20
50
23 29 31 37 41 43 47 

Factorial using recursion

In [8]:
n=int(input())
def fact(n):
    if n==0 or n==1:
        return 1
    else:
        return n * fact(n-1)
print(fact(n))

6
720


Square of numbers using lambda

In [12]:
n=int(input())
square=lambda x : x*x
print(square(n))

5
25


Find the second largest element in a list

In [16]:
n=int(input())
arr=list(map(int,input().split()))
max=arr[0]
secmax=arr[0]
for i in range(1,n):
    if arr[i] > arr[0]:
        secmax=max
        max=arr[i]
    elif arr[i] > secmax and arr[i]!=max:
        secmax=arr[i]
print(secmax)
        
        


5
12 45 41 7 98
41


Count frequency of characters in a string

In [21]:
s=input()
freq={}
for ch in s:
    if ch in freq:
        freq[ch]=freq[ch]+1
    else:
        freq[ch]=1
for ch in freq:
    print(ch,freq[ch])
        

helloo
h 1
e 1
l 2
o 2


Calculate area of a circle using math library

In [6]:
import math
r=int(input())
area=math.pi*r*r
print("Area of circle: ",area)

5
Area of circle:  78.53981633974483


Reverse a string without using built‑in reverse

In [12]:
s=input()
rev=""
for i in range(len(s)-1,-1,-1):
    rev+=s[i]
print(rev)

hello
olleh


Remove duplicates from a list

In [2]:
n=int(input())
a=list(map(int,input().split()))
result=[]
for x in a:
    if x not in result:
        result.append(x)
print(result)

5 
10 20 10 30 40
[10, 20, 30, 40]


Merge two dictionaries

In [4]:
dict1 = {"a": 10, "b": 20}
dict2 = {"c": 30, "d": 40}
for key in dict2:
    dict1[key] = dict2[key]
print(dict1)

{'a': 10, 'b': 20, 'c': 30, 'd': 40}


Fibonacci series using recursion

n=int(input())
def fibo(n):
    if n==0:
        return 0
    elif n==1:
        return 1
    for i in range(2,n+1):
        return fibo(n-1)+fibo(n-2)
for i in range(n):
    print(fibo(i),end=" ")

# PYTHON FUNCTION ASSIGNMENT

1.Write a function calculate(a, b, operation) that performs addition, subtraction, multiplication, or division based on the supplied operation.

In [10]:
def calculate(a, b, operation):
    if operation == "+":
        return a + b
    elif operation == "-":
        return a - b
    elif operation == "*":
        return a * b
    elif operation == "/":
        return a / b

a = int(input())
b = int(input())
operation = input()
print(calculate(a, b, operation))

10
5
+
15


2.Write a function sum_numbers(*args) that accepts any number of arguments and returns their sum.

In [12]:
def sum_numbers(*args):
    total = 0
    for x in args:
        total = total + x
    return total
n = int(input())
a = list(map(int, input().split()))
print(sum_numbers(*a))

5
10 20 30 40 50
150


3.Write a function employee(**args) that accepts employee information such as name, ID, department and salary, then displays the information.

In [13]:
def employee(**args):
    for key in args:
        print(key, ":", args[key])
name = input()
id = input()
department = input()
salary = input()
employee(name=name, ID=id, department=department, salary=salary)

sandhiya
101
aiml
45000
name : sandhiya
ID : 101
department : aiml
salary : 45000


4.Write a function remove_duplicates(lst) that returns a list containing only unique elements while preserving their original order.

In [14]:
def remove_duplicates(lst):
    result = []
    for x in lst:
        if x not in result:
            result.append(x)
    return result
n = int(input())
lst = list(map(int, input().split()))
print(remove_duplicates(lst))

5
10 20 30 20 10
[10, 20, 30]


5.Using a lambda function, sort a list of tuples based on the second element. Example: [(1,5), (2,3), (4,1)].

In [15]:
n = int(input())
lst = []
for i in range(n):
    a, b = map(int, input().split())
    lst.append((a, b))
lst.sort(key=lambda x: x[1])
print(lst)

3 
1 5
2 3
4 1
[(4, 1), (2, 3), (1, 5)]


# NUMPY ASSIGNMENT

In [16]:
import numpy as np

Student Marks Array

In [17]:
marks = np.array([78, 65, 89, 56, 92])
print("Array:", marks)
print("Dimension:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)

Array: [78 65 89 56 92]
Dimension: 1
Shape: (5,)
Size: 5
Data type: int32


Student Marks Access

In [18]:
marks = np.array([72, 85, 64, 90, 76])
print("Array:", marks)
print("First student:", marks[0])
print("Third student:", marks[2])
print("Last student:", marks[-1])
print("First three students:", marks[0:3])
print("Second to fourth:", marks[1:4])

Array: [72 85 64 90 76]
First student: 72
Third student: 64
Last student: 76
First three students: [72 85 64]
Second to fourth: [85 64 90]


Subject-wise Marks

In [19]:
marks = np.array([
    78, 85, 90,
    65, 72, 80,
    88, 91, 84,
    56, 62, 70,
    95, 89, 92
])

matrix = marks.reshape(5, 3)
print("Marks:")
print(matrix)
print("Shape:", matrix.shape)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Shape: (5, 3)


Internal and External Marks

In [20]:
internal = np.array([20, 18, 22, 19, 21])
external = np.array([65, 70, 60, 68, 72])
final_marks = internal + external
print("Internal:", internal)
print("External:", external)
print("Final Marks:", final_marks)

Internal: [20 18 22 19 21]
External: [65 70 60 68 72]
Final Marks: [85 88 82 87 93]


Pass Percentage Analysis

In [21]:
marks = np.array([45, 78, 56, 32, 91])
passed = marks >= 50
print("Marks:", marks)
print("Boolean result:", passed)
print("Passed marks:", marks[passed])

Marks: [45 78 56 32 91]
Boolean result: [False  True  True False  True]
Passed marks: [78 56 91]


Average Marks

In [23]:
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

average = np.mean(marks, axis=1)
print("Marks:")
print(marks)
print("Average of each student:", average)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Average of each student: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


Class Performance Statistics

In [24]:
marks = np.array([67, 82, 91, 74, 58])
print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard Deviation: 11.46472851837321


Subject-wise Performance

In [25]:
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
subject_total = np.sum(marks, axis=0)
print("Marks:")
print(marks)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


Student-wise Performance

In [26]:
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
student_total = np.sum(marks, axis=1)
print("Student totals:", student_total)

Student totals: [253 217 263 188 276]


Student Ranking

In [27]:
marks = np.array([245, 278, 219, 290, 256])
sorted_marks = np.sort(marks)[::-1]
print("Original marks:", marks)
print("Ranked marks:", sorted_marks)
for i in range(len(sorted_marks)):
    print("Rank", i + 1, ":", sorted_marks[i])

Original marks: [245 278 219 290 256]
Ranked marks: [290 278 256 245 219]
Rank 1 : 290
Rank 2 : 278
Rank 3 : 256
Rank 4 : 245
Rank 5 : 219


Duplicate Marks Analysis

In [28]:
marks = np.array([85, 92, 85, 76, 92])
unique_marks = np.unique(marks)
print("Marks:", marks)
print("Unique marks:", unique_marks)

Marks: [85 92 85 76 92]
Unique marks: [76 85 92]


Missing Marks

In [29]:
marks = np.array([78, 85, np.nan, 92, 67])
average = np.nanmean(marks)
print("Marks:", marks)
print("Average:", average)

Marks: [78. 85. nan 92. 67.]
Average: 80.5


Grade Classification

In [30]:
marks = np.array([95, 82, 74, 61, 45])
grades = np.select(
    [
        marks >= 90,
        marks >= 80,
        marks >= 70,
        marks >= 60
    ],
    [
        "A",
        "B",
        "C",
        "D"
    ],
    default="F"
)

print("Marks:", marks)
print("Grades:", grades)

Marks: [95 82 74 61 45]
Grades: ['A' 'B' 'C' 'D' 'F']


Random Marks Generation

In [31]:
marks = np.random.randint(0, 101, 5)
print("Generated marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

Generated marks: [59 42 88 81 43]
Total: 313
Average: 62.6
Highest: 88
Lowest: 42


Student Performance Analysis

In [32]:
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
highest = np.max(marks, axis=1)
lowest = np.min(marks, axis=1)
class_average = np.mean(marks)
print("Marks:")
print(marks)
print("\nStudent Total:", total)
print("Student Average:", average)
print("Highest mark:", highest)
print("Lowest mark:", lowest)
print("\nClass Average:", class_average)
print("Students above class average:")

for i in range(len(average)):
    if average[i] > class_average:
        print("Student", i + 1)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Student Total: [253 217 263 188 276]
Student Average: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]
Highest mark: [90 80 91 70 95]
Lowest mark: [78 65 84 56 89]

Class Average: 79.8
Students above class average:
Student 1
Student 3
Student 5
